<script lang="ts">
	import Flourish from '$lib/components/design/Flourish.svelte';
</script>

<article
	class="max-w-prose mx-auto px-5 py-14 text-left text-ink leading-[1.75] [&_p]:mb-4 [&_li>p]:mb-2 [&_ul]:list-none [&_ul]:mt-2 [&_ul]:mb-6 [&_ul]:mx-0 [&_ul]:pl-1 [&_li]:relative [&_li]:pl-[1.6rem] [&_li]:mb-[0.85rem] [&_li::before]:content-['❧'] [&_li::before]:absolute [&_li::before]:left-0 [&_li::before]:top-0 [&_li::before]:text-leaf-soft"
>
	<header class="mb-12">
		<span class="label-specimen block mb-3">Appendix · Records of the Archive</span>
		<h1 class="font-display font-semibold text-4xl sm:text-5xl leading-tight mb-3">Privacy Policy</h1>
		<p class="font-mono text-sm text-ink-soft">Effective date: December 18, 2024</p>
		<div class="mt-6" aria-hidden="true">
			<Flourish width={230} color="var(--ink-faint)" />
		</div>
	</header>

	<p
		class="first-letter:float-left first-letter:font-display first-letter:font-semibold first-letter:text-[3.4em] first-letter:leading-[0.78] first-letter:pr-[0.1em] first-letter:pt-[0.06em] first-letter:text-petal"
	>
		Lars Boese (&quot;I&quot;, &quot;me&quot;, or &quot;my&quot;) operates the
		<a
			class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
			href="https://www.ayakobot.com">https://www.ayakobot.com</a
		>
		website and the &quot;Ayako#6768&quot; Discord Bot, with unique Discord User-ID &quot;650691698409734151&quot;
		(hereinafter referred to as the &quot;Service&quot;).
	</p>
	<p>
		This page informs you of my policies regarding the collection, use and disclosure of personal data
		when you use my Service and the choices you have associated with that data.
	</p>
	<p>
		I use your data to provide and improve the Service. By using the Service, you agree to the
		collection and use of information in accordance with this policy. Unless otherwise defined in this
		Privacy Policy, the terms used in this Privacy Policy have the same meanings as in my Terms and
		Conditions, accessible from
		<a
			class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
			href="/terms">https://www.ayakobot.com/terms</a
		>
	</p>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Definitions</h2>
		<ul>
			<li>
				<span class="font-display italic">Service</span>
				<p>
					Service is the
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://www.ayakobot.com">https://www.ayakobot.com</a
					>
					website and the &quot;Ayako#6768&quot; Discord Bot, with unique Discord User-ID &quot;650691698409734151&quot;
					developed and maintained by Lars Boese
				</p>
			</li>
			<li>
				<span class="font-display italic">Personal Data</span>
				<p>
					Personal Data means data about a living individual who can be identified from those data (or
					from those and other information either in my possession or likely to come into my possession).
				</p>
			</li>
			<li>
				<span class="font-display italic">Usage Data</span>
				<p>
					Usage Data is data collected automatically either generated by the use of the Service or from
					the Service infrastructure itself (for example, the duration of a page visit).
				</p>
			</li>
			<li>
				<span class="font-display italic">Cookies</span>
				<p>Cookies are small files stored on your device (computer or mobile device).</p>
			</li>
			<li>
				<span class="font-display italic">Data Controller</span>
				<p>
					Data Controller means the natural or legal person who (either alone or jointly or in common
					with other persons) determines the purposes for which and the manner in which any personal
					information are, or are to be, processed.
				</p>
				<p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
			</li>
			<li>
				<span class="font-display italic">Data Processors (or Service Providers)</span>
				<p>
					Data Processor (or Service Provider) means any natural or legal person who processes the data
					on behalf of the Data Controller.
				</p>
				<p>
					I may use the services of various Service Providers in order to process your data more
					effectively.
				</p>
			</li>
			<li>
				<span class="font-display italic">Data Subject (or User)</span>
				<p>
					Data Subject is any living individual who is using my Service and is the subject of Personal
					Data.
				</p>
			</li>
		</ul>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Information Collection and Use</h2>
		<p>
			I collect several different types of information for various purposes to provide and improve my
			Service to you.
		</p>

		<h3 class="font-display font-semibold text-xl mt-8 mb-3">Types of Data Collected</h3>

		<h4 class="font-display font-semibold italic text-lg mt-6 mb-2">Personal Data</h4>
		<p>
			While using my Service, I may ask you to provide me with certain personally identifiable
			information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally
			identifiable information may include, but is not limited to:
		</p>
		<ul>
			<li>Your Discord User ID</li>
			<li>Your Discord User Name</li>
			<li>Your Joined Discord Servers</li>
			<li>Cookies and Usage Data</li>
		</ul>

		<h4 class="font-display font-semibold italic text-lg mt-6 mb-2">Usage Data</h4>
		<p>
			I may collect information on how the Service is accessed and used (&quot;Usage Data&quot;). This
			Usage Data may include information such as your computer&#39;s Internet Protocol address (e.g. IP
			address), browser type, browser version, the pages of my Service that you visit, the time and
			date of your visit, the time spent on those pages, unique device identifiers and other diagnostic
			data. This is all stored by google, and not me.
		</p>

		<h4 class="font-display font-semibold italic text-lg mt-6 mb-2">Tracking &amp; Cookies Data</h4>
		<p>
			I use cookies and similar tracking technologies to track the activity on my Service and I hold
			certain information.
		</p>
		<p>
			Cookies are files with a small amount of data which may include an anonymous unique identifier.
			Cookies are sent to your browser from a website and stored on your device. Other tracking
			technologies are also used such as beacons, tags and scripts to collect and track information and
			to improve and analyse my Service.
		</p>
		<p>
			You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
			However, if you do not accept cookies, you may not be able to use some portions of my Service.
		</p>
		<p>Examples of Cookies I use:</p>
		<ul>
			<li>
				<span class="font-display italic">Session Cookies</span>
				<p>
					I use Session Cookies to keep you logged in to Discord on my site. I also use Hotjar, Google
					Analytics and Cloudflare Analytics, which use cookies for general statistical data to help me
					learn and grow about how to make a better user experience.
				</p>
			</li>
		</ul>

		<h4 class="font-display font-semibold italic text-lg mt-6 mb-2">Message Content Data</h4>
		<p>
			My Service may also collect and log information stored in your Message Content (&quot;Message
			Content Data&quot;), depending on whether the Server you edit or delete your Message on has the
			Service Feature &quot;Message Logging&quot; enabled. Message Content that can lead back to you is
			not stored outside of Discord. You may opt-out of Message Logging by disabling it in your Discord
			Server or leaving the Discord Servers which have this feature enabled. Message Content Data may
			include information such as Message Content, Message Embeds, Message Attachments and Message
			Components.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Use of Data</h2>
		<p>Lars Boese uses the collected data for various purposes:</p>
		<ul>
			<li>To provide and maintain my Service</li>
			<li>To notify you about changes to my Service</li>
			<li>
				To allow you to participate in interactive features of my Service when you choose to do so
			</li>
			<li>To provide customer support</li>
			<li>To gather analysis or valuable information so that I can improve my Service</li>
			<li>To monitor the usage of my Service</li>
			<li>To detect, prevent and address technical issues</li>
			<li></li>
		</ul>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">
			Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)
		</h2>
		<p>
			If you are from the European Economic Area (EEA), Lars Boese legal basis for collecting and using
			the personal information described in this Privacy Policy depends on the Personal Data I collect
			and the specific context in which I collect it.
		</p>
		<p>Lars Boese may process your Personal Data because:</p>
		<ul>
			<li>I need to perform a contract with you</li>
			<li>You have given me permission to do so</li>
			<li>The processing is in my legitimate interests and it is not overridden by your rights</li>
			<li>For payment processing purposes</li>
			<li>To comply with the law</li>
		</ul>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Retention of Data</h2>
		<p>
			Lars Boese will retain your Personal Data only for as long as is necessary for the purposes set
			out in this Privacy Policy. I will retain and use your Personal Data to the extent necessary to
			comply with my legal obligations (for example, if I am required to retain your data to comply
			with applicable laws), resolve disputes and enforce my legal agreements and policies.
		</p>
		<p>
			Lars Boese will also retain Usage Data for internal analysis purposes. Usage Data is generally
			retained for a shorter period of time, except when this data is used to strengthen the security
			or to improve the functionality of my Service, or I am legally obligated to retain this data for
			longer periods.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Transfer of Data</h2>
		<p>
			Your information, including Personal Data, may be transferred to - and maintained on - computers
			located outside of your state, province, country or other governmental jurisdiction where the
			data protection laws may differ from those of your jurisdiction.
		</p>
		<p>
			If you are located outside Germany and choose to provide information to us, please note that I
			transfer the data, including Personal Data, to Germany and process it there.
		</p>
		<p>
			Your consent to this Privacy Policy followed by your submission of such information represents
			your agreement to that transfer.
		</p>
		<p>
			Lars Boese will take all the steps reasonably necessary to ensure that your data is treated
			securely and in accordance with this Privacy Policy and no transfer of your Personal Data will
			take place to an organisation or a country unless there are adequate controls in place including
			the security of your data and other personal information.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Disclosure of Data</h2>

		<h3 class="font-display font-semibold text-xl mt-8 mb-3">Legal Requirements</h3>
		<p>
			Lars Boese may disclose your Personal Data in the good faith belief that such action is necessary
			to:
		</p>
		<ul>
			<li>comply with a legal obligation</li>
			<li>protect and defend the rights or property of Lars Boese</li>
			<li>prevent or investigate possible wrongdoing in connection with the Service</li>
			<li>protect the personal safety of users of the Service or the public</li>
			<li>protect against legal liability</li>
		</ul>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Security of Data</h2>
		<p>
			The security of your data is important to me but remember that no method of transmission over the
			Internet or method of electronic storage is 100% secure. While I strive to use commercially
			acceptable means to protect your Personal Data, I cannot guarantee its absolute security.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">
			Your Data Protection Rights under the General Data Protection Regulation (GDPR)
		</h2>
		<p>
			If you are a resident of the European Economic Area (EEA), you have certain data protection
			rights. Lars Boese aims to take reasonable steps to allow you to correct, amend, delete or limit
			the use of your Personal Data.
		</p>
		<p>
			If you wish to be informed about what Personal Data I hold about you and if you want it to be
			removed from my systems, please contact me.
		</p>
		<p>In certain circumstances, you have the following data protection rights:</p>
		<ul>
			<li>
				<span class="font-display italic">
					The right to access, update or delete the information I have on you.
				</span>
				<p>
					Whenever made possible, you can access, update or request deletion of your Personal Data by
					contacting me.
				</p>
			</li>
			<li>
				<span class="font-display italic">The right of rectification.</span>
				<p>
					You have the right to have your information rectified if that information is inaccurate or
					incomplete.
				</p>
			</li>
			<li>
				<span class="font-display italic">The The right to object.</span>
				<p>You have the right to object to my processing of your Personal Data.</p>
			</li>
			<li>
				<span class="font-display italic">The right of restriction.</span>
				<p>
					You have the right to request that I restrict the processing of your personal information.
				</p>
			</li>
			<li>
				<span class="font-display italic">The right to data portability.</span>
				<p>
					You have the right to be provided with a copy of the information I have on you in a structured,
					machine-readable and commonly used format.
				</p>
			</li>
			<li>
				<span class="font-display italic">The right to withdraw consent.</span>
				<p>
					You also have the right to withdraw your consent at any time where Lars Boese relied on your
					consent to process your personal information.
				</p>
			</li>
		</ul>
		<p>Please note that I may ask you to verify your identity before responding to such requests.</p>
		<p>
			You have the right to complain to a Data Protection Authority about my collection and use of your
			Personal Data. For more information, please contact your local data protection authority in the
			European Economic Area (EEA).
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Service Providers</h2>
		<p>
			I may employ third party companies and individuals to facilitate my Service (&quot;Service
			Providers&quot;), provide the Service on my behalf, perform Service-related services or assist me
			in analysing how my Service is used.
		</p>
		<p>
			These third parties have access to your Personal Data only to perform these tasks on my behalf
			and are obligated not to disclose or use it for any other purpose.
		</p>

		<h3 class="font-display font-semibold text-xl mt-8 mb-3">Analytics</h3>
		<p>I may use third-party Service Providers to monitor and analyse the use of my Service.</p>
		<ul>
			<li>
				<span class="font-display italic">Hotjar</span>
				<p>
					Hotjar is an all-in-one analytics and feedback tool that helps website owners and marketers
					understand how users interact with their website. It offers a suite of tools to track and
					analyze user behavior, as well as tools to collect user feedback and insights.
				</p>
				<p>
					You can opt-out of having made your activity on the Service available to Hotjar by disabling
					Third-Party Cookies.
				</p>
				<p>
					For more information on the privacy practices of Hotjar, please visit the Hotjar Privacy &amp;
					Terms web page:
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://www.hotjar.com/privacy/"
					>
						Hotjar Privacy Policy
					</a>
				</p>
			</li>
			<li>
				<span class="font-display italic">Google Analytics</span>
				<p>
					Google Analytics is a web analytics service offered by Google that allows website owners and
					marketers to track and analyze website traffic and user behavior. It provides valuable insights
					into how visitors interact with a website, including information about where they come from,
					how long they stay, which pages they visit, and what actions they take on the site.
				</p>
				<p>
					You can opt-out of having made your activity on the Service available to Google by disabling
					Third-Party Cookies.
				</p>
				<p>
					For more information on the privacy practices of Google, please visit the Google Privacy &amp;
					Terms web page:
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://policies.google.com/privacy/"
					>
						Google Privacy Policy
					</a>
				</p>
			</li>
			<li>
				<span class="font-display italic">Cloudflare Analytics</span>
				<p>
					Cloudflare Analytics is a web analytics service provided by Cloudflare, a company that offers
					content delivery, DDoS protection, and other web performance and security services. Cloudflare
					Analytics provides insights into website traffic and visitor behavior, helping website owners
					and administrators make data-driven decisions to optimize their site's performance and
					security.
				</p>
				<p>
					You can opt-out of having made your activity on the Service available to Cloudflare by
					disabling Third-Party Cookies.
				</p>
				<p>
					For more information on the privacy practices of Cloudflare, please visit the Cloudflare
					Privacy &amp; Terms web page:
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://www.cloudflare.com/privacypolicy/"
					>
						Cloudflare Privacy Policy
					</a>
				</p>
			</li>
		</ul>

		<h3 class="font-display font-semibold text-xl mt-8 mb-3">Advertising</h3>
		<p>
			I may use third-party Service Providers to show advertisements to you to help support and
			maintain my Service.
		</p>
		<ul>
			<li>
				<span class="font-display italic">Google AdSense &amp; DoubleClick Cookie</span>
				<p>
					Google, as a third party vendor, uses cookies to serve ads on my Service. Google&#39;s use of
					the DoubleClick cookie enables it and its partners to serve ads to my users based on their
					visit to my Service or other websites on the Internet.
				</p>
				<p>
					You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting
					the Google Ads Settings web page:
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://www.google.com/ads/preferences/"
					>
						Google Preferences
					</a>
				</p>
			</li>
		</ul>

		<h3 class="font-display font-semibold text-xl mt-8 mb-3">Payments</h3>
		<p>
			I may provide paid products and/or services within the Service. In that case, I use third-party
			services for payment processing (e.g. payment processors).
		</p>
		<p>
			I will not store or collect your payment card details. That information is provided directly to
			my third-party payment processors whose use of your personal information is governed by their
			Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the
			PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American
			Express and Discover. PCI-DSS requirements help ensure the secure handling of payment
			information.
		</p>
		<p>The payment processors I work with are:</p>
		<ul>
			<li>
				<span class="font-display italic">PayPal</span>
				<p>
					Their Privacy Policy can be viewed at
					<a
						class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
						href="https://www.paypal.com/webapps/mpp/ua/privacy-full"
					>
						PayPal Privacy Policy
					</a>
				</p>
			</li>
		</ul>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Links to Other Sites</h2>
		<p>
			My Service may contain links to other sites that are not operated by me. If you click a third
			party link, you will be directed to that third party&#39;s site. I uly advise you to review the
			Privacy Policy of every site you visit.
		</p>
		<p>
			I have no control over and assume no responsibility for the content, privacy policies or
			practices of any third party sites or services.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Children&#39;s Privacy</h2>
		<p>My Service does not address anyone under the age of 13 (&quot;Children&quot;).</p>
		<p>
			I do not knowingly collect personally identifiable information from anyone under the age of 13.
			If you are a parent or guardian and you are aware that your Child has provided me with Personal
			Data, please contact me. If we become aware that I have collected Personal Data from children
			without verification of parental consent, I take steps to remove that information from my
			servers.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Changes to This Privacy Policy</h2>
		<p>
			I may update my Privacy Policy from time to time. I will notify you of any changes by posting the
			new Privacy Policy on this page.
		</p>
		<p>
			I will let you know via prominent notice on my Discord Server (<a
				class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
				href="https://discord.com/channels/298954459172700181/765743834118225961"
			>
				#ayako-updates
			</a>
			news-channel on
			<a
				class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
				href="https://discord.gg/animekos"
			>
				Animekos
			</a>), prior to the change becoming effective and update the &quot;effective date&quot; at the
			top of this Privacy Policy.
		</p>
		<p>
			You are advised to review this Privacy Policy periodically for any changes. Changes to this
			Privacy Policy are effective when they are posted on this page.
		</p>
	</section>

	<section>
		<h2 class="font-display font-semibold text-2xl mt-12 mb-4">Contact me</h2>
		<p>
			If you have any questions about this Privacy Policy, please contact me by email:
			<a
				class="text-petal bg-[linear-gradient(to_right,var(--petal),var(--petal))] bg-[length:100%_1px] bg-no-repeat bg-[position:0_100%] [transition:background-size_0.35s_var(--ease-organic)] hover:bg-[length:100%_2px]"
				href="mailto:dev@ayakobot.com"
			>
				<span>dev@ayakobot.com</span>
			</a>
		</p>
	</section>

	<span data-ccpa-link="1"></span>
</article>
